-- ==========================================
-- CONSOLIDATED SUPABASE SCHEMA + SEED SCRIPT
-- Project ID: htlikyvrtujtizdlmgew
-- ==========================================

-- SET SEARCH PATH TO INCLUDE EXTENSIONS & AUTH SCHEMAS
SET search_path TO public, extensions, auth;

-- 1. FACTORY RESET PUBLIC SCHEMA (Resolves all "must be owner of table" errors)
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

-- Restore standard permissions
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO anon;
GRANT ALL ON SCHEMA public TO authenticated;
GRANT ALL ON SCHEMA public TO service_role;

-- SET SEARCH PATH (Ensure queries default to public and find extensions/auth)
SET search_path TO public, extensions, auth;

-- 2. CLEAN UP OLD AUTH USERS (Prevents duplicate conflicts and satisfies foreign keys)
DELETE FROM auth.identities WHERE user_id IN (SELECT id FROM auth.users WHERE email IN ('admin@example.com', 'ketua@example.com', 'sekretaris@example.com', 'anggota@example.com'));
DELETE FROM auth.sessions WHERE user_id IN (SELECT id FROM auth.users WHERE email IN ('admin@example.com', 'ketua@example.com', 'sekretaris@example.com', 'anggota@example.com'));
DELETE FROM auth.users WHERE email IN ('admin@example.com', 'ketua@example.com', 'sekretaris@example.com', 'anggota@example.com');

-- 3. ENABLE DATABASE EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 4. CREATE ENUMS
CREATE TYPE article_status_enum AS ENUM ('Published', 'Draft');
CREATE TYPE service_status_enum AS ENUM ('pending', 'processed');
CREATE TYPE letter_status_enum AS ENUM ('menunggu', 'dicek_sekretaris', 'menunggu_ttd_ketua', 'selesai', 'ditolak');

-- 5. CREATE TABLES
-- TABEL ROLES
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- TABEL USERS (Maps to auth.users)
CREATE TABLE users (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role_id BIGINT DEFAULT 4,
    nia VARCHAR(20) UNIQUE,
    phone VARCHAR(20),
    photo VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL
);

-- TABEL ARTICLES
CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    date DATE NOT NULL,
    author VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status article_status_enum NOT NULL DEFAULT 'Draft',
    image VARCHAR(255),
    sections JSONB,
    gallery JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- TABEL ARTICLES OLD
CREATE TABLE articles_old (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- TABEL SERVICE REQUESTS
CREATE TABLE service_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    service_type VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    status service_status_enum NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- TABEL SURAT MASUK
CREATE TABLE surat_masuk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_surat VARCHAR(255) NOT NULL,
    tanggal_masuk DATE NOT NULL,
    pengirim VARCHAR(255) NOT NULL,
    perihal TEXT NOT NULL,
    file_path VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- TABEL SURAT KELUAR
CREATE TABLE surat_keluar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_surat VARCHAR(255) NOT NULL,
    tanggal_keluar DATE NOT NULL,
    penerima VARCHAR(255) NOT NULL,
    perihal TEXT NOT NULL,
    file_path VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- TABEL LETTER REQUESTS
CREATE TABLE letter_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    type VARCHAR(100) NOT NULL,
    purpose TEXT NOT NULL,
    phone VARCHAR(20),
    status letter_status_enum DEFAULT 'menunggu',
    rejection_reason TEXT,
    rejected_by UUID,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_rejected_by FOREIGN KEY (rejected_by) REFERENCES users(id) ON DELETE SET NULL
);

-- TABEL LETTER DOCUMENTS
CREATE TABLE letter_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_id BIGINT NOT NULL UNIQUE,
    letter_number VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    issue_date DATE NOT NULL,
    sekretaris_signature VARCHAR(255),
    sekretaris_stamp VARCHAR(255),
    ketua_signature VARCHAR(255),
    processed_by_sekretaris UUID,
    approved_by_ketua UUID,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_letter FOREIGN KEY (letter_id) REFERENCES letter_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_processed_by FOREIGN KEY (processed_by_sekretaris) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_approved_by FOREIGN KEY (approved_by_ketua) REFERENCES users(id) ON DELETE SET NULL
);

-- 6. DISABLE ROW LEVEL SECURITY AND ADD PERMISSIVE POLICIES
-- NOTE: In Supabase, ALTER TABLE ... DISABLE ROW LEVEL SECURITY only works for
-- the table owner (postgres). For other roles (anon, authenticated), we need
-- explicit permissive policies to allow all operations.

-- First, enable RLS (required for policies to be evaluated) then add permissive policies
DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN SELECT unnest(ARRAY[
        'roles', 'users', 'articles', 'articles_old', 
        'service_requests', 'surat_masuk', 'surat_keluar', 
        'letter_requests', 'letter_documents'
    ])
    LOOP
        -- Enable RLS (needed so policies are evaluated)
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);
        
        -- Drop existing policies if any
        EXECUTE format('DROP POLICY IF EXISTS "allow_all_select" ON %I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "allow_all_insert" ON %I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "allow_all_update" ON %I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "allow_all_delete" ON %I', tbl);
        
        -- Create permissive policies for all roles
        EXECUTE format('CREATE POLICY "allow_all_select" ON %I FOR SELECT USING (true)', tbl);
        EXECUTE format('CREATE POLICY "allow_all_insert" ON %I FOR INSERT WITH CHECK (true)', tbl);
        EXECUTE format('CREATE POLICY "allow_all_update" ON %I FOR UPDATE USING (true) WITH CHECK (true)', tbl);
        EXECUTE format('CREATE POLICY "allow_all_delete" ON %I FOR DELETE USING (true)', tbl);
    END LOOP;
END $$;

-- 7. SEED ROLES FIRST (Must exist BEFORE trigger fires on auth.users insert)
INSERT INTO roles (id, name, description) VALUES
(1, 'super_admin', 'Manajemen user dan data aplikasi'),
(2, 'ketua', 'Menyetujui surat, upload TTD'),
(3, 'sekretaris', 'Proses surat, upload TTD + stempel'),
(4, 'anggota', 'Mengajukan surat, lihat riwayat')
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name, description = EXCLUDED.description;

-- 8. DEFINE TRIGGERS AND FUNCTIONS
-- AUTO PROFILE SYNC FUNCTION
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, name, email, role_id, nia, phone)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', 'Anggota Baru'),
    new.email,
    COALESCE((new.raw_user_meta_data->>'role_id')::BIGINT, 4),
    new.raw_user_meta_data->>'nia',
    new.raw_user_meta_data->>'phone'
  )
  ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name, 
      email = EXCLUDED.email,
      role_id = EXCLUDED.role_id,
      nia = EXCLUDED.nia,
      phone = EXCLUDED.phone;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- DROP OLD TRIGGER IF EXISTS (Prevents stale reference after schema reset)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- REGISTER PROFILE SYNC TRIGGER
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- AUTO UPDATED_AT TIMESTAMP FUNCTION
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- REGISTER TIMESTAMP TRIGGER
CREATE TRIGGER set_timestamp_letter_requests
BEFORE UPDATE ON letter_requests
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

-- ARTICLES SEED
INSERT INTO articles (id, title, slug, date, author, category, content, status) VALUES
(1, 'Kegiatan Kajian Rutin', 'kegiatan-kajian-rutin', '2026-01-15', 'Admin', 'Kegiatan', 'Kajian rutin mingguan untuk meningkatkan wawasan keislaman.', 'Published'),
(2, 'Pelatihan Kepemimpinan', 'pelatihan-kepemimpinan', '2026-02-10', 'Admin', 'Kegiatan', 'Program kepemimpinan untuk pelajar aktif.', 'Published'),
(3, 'Bakti Sosial Pelajar', 'bakti-social-pelajar', '2026-03-05', 'Admin', 'Sosial', 'Kegiatan sosial untuk membantu masyarakat sekitar.', 'Published')
ON CONFLICT (id) DO UPDATE 
SET title = EXCLUDED.title, slug = EXCLUDED.slug, date = EXCLUDED.date, author = EXCLUDED.author, category = EXCLUDED.category, content = EXCLUDED.content, status = EXCLUDED.status;

-- 9. PROGRAMMATIC SEED OF AUTH USERS
-- Tambah Admin (admin@example.com / admin123)
DO $$ 
DECLARE 
    v_user_id UUID := gen_random_uuid();
    v_email TEXT := 'admin@example.com';
BEGIN
    INSERT INTO auth.users (
        id, instance_id, aud, role, email, encrypted_password, 
        email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
        confirmation_token, email_change, email_change_token_new, recovery_token
    ) VALUES (
        v_user_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 
        v_email, crypt('password', gen_salt('bf')), NOW(),
        '{"provider":"email","providers":["email"]}'::jsonb,
        '{"name":"Super Admin","role_id":1,"nia":"00000","phone":"08123456789"}'::jsonb, NOW(), NOW(),
        '', '', '', ''
    );

    INSERT INTO auth.identities (
        id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
    ) VALUES (
        gen_random_uuid(), v_user_id, v_user_id::text, 
        json_build_object('sub', v_user_id::text, 'email', v_email)::jsonb,
        'email', NOW(), NOW(), NOW()
    );
END $$;

-- Tambah Ketua (ketua@example.com / ketua123)
DO $$ 
DECLARE 
    v_user_id UUID := gen_random_uuid();
    v_email TEXT := 'ketua@example.com';
BEGIN
    INSERT INTO auth.users (
        id, instance_id, aud, role, email, encrypted_password, 
        email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
        confirmation_token, email_change, email_change_token_new, recovery_token
    ) VALUES (
        v_user_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 
        v_email, crypt('password', gen_salt('bf')), NOW(),
        '{"provider":"email","providers":["email"]}'::jsonb,
        '{"name":"Wildan","role_id":2,"nia":"11111","phone":"08123456781"}'::jsonb, NOW(), NOW(),
        '', '', '', ''
    );

    INSERT INTO auth.identities (
        id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
    ) VALUES (
        gen_random_uuid(), v_user_id, v_user_id::text, 
        json_build_object('sub', v_user_id::text, 'email', v_email)::jsonb,
        'email', NOW(), NOW(), NOW()
    );
END $$;

-- Tambah Sekretaris (sekretaris@example.com / sekretaris123)
DO $$ 
DECLARE 
    v_user_id UUID := gen_random_uuid();
    v_email TEXT := 'sekretaris@example.com';
BEGIN
    INSERT INTO auth.users (
        id, instance_id, aud, role, email, encrypted_password, 
        email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
        confirmation_token, email_change, email_change_token_new, recovery_token
    ) VALUES (
        v_user_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 
        v_email, crypt('password', gen_salt('bf')), NOW(),
        '{"provider":"email","providers":["email"]}'::jsonb,
        '{"name":"Ahmad Fauzi","role_id":3,"nia":"22222","phone":"08123456782"}'::jsonb, NOW(), NOW(),
        '', '', '', ''
    );

    INSERT INTO auth.identities (
        id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
    ) VALUES (
        gen_random_uuid(), v_user_id, v_user_id::text, 
        json_build_object('sub', v_user_id::text, 'email', v_email)::jsonb,
        'email', NOW(), NOW(), NOW()
    );
END $$;

-- Tambah Anggota (anggota@example.com / anggota123)
DO $$ 
DECLARE 
    v_user_id UUID := gen_random_uuid();
    v_email TEXT := 'anggota@example.com';
BEGIN
    INSERT INTO auth.users (
        id, instance_id, aud, role, email, encrypted_password, 
        email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
        confirmation_token, email_change, email_change_token_new, recovery_token
    ) VALUES (
        v_user_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 
        v_email, crypt('password', gen_salt('bf')), NOW(),
        '{"provider":"email","providers":["email"]}'::jsonb,
        '{"name":"Budi Santoso","role_id":4,"nia":"12345","phone":"08123456789"}'::jsonb, NOW(), NOW(),
        '', '', '', ''
    );

    INSERT INTO auth.identities (
        id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
    ) VALUES (
        gen_random_uuid(), v_user_id, v_user_id::text, 
        json_build_object('sub', v_user_id::text, 'email', v_email)::jsonb,
        'email', NOW(), NOW(), NOW()
    );
END $$;

-- 10. MANUAL FALLBACK: Insert profiles into public.users directly
-- (Safety net in case the trigger on auth.users failed silently)
INSERT INTO public.users (id, name, email, role_id, nia, phone)
SELECT 
  u.id,
  COALESCE(u.raw_user_meta_data->>'name', 'User'),
  u.email,
  COALESCE((u.raw_user_meta_data->>'role_id')::BIGINT, 4),
  u.raw_user_meta_data->>'nia',
  u.raw_user_meta_data->>'phone'
FROM auth.users u
WHERE u.email IN ('admin@example.com', 'ketua@example.com', 'sekretaris@example.com', 'anggota@example.com')
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, 
    email = EXCLUDED.email,
    role_id = EXCLUDED.role_id,
    nia = EXCLUDED.nia,
    phone = EXCLUDED.phone;

-- 11. SYNC AUTO-INCREMENT SEQUENCES SAFELY
DO $$
DECLARE
    t RECORD;
    seq TEXT;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
          AND table_name IN ('roles', 'articles', 'articles_old', 'service_requests', 'surat_masuk', 'surat_keluar', 'letter_requests', 'letter_documents')
    LOOP
        seq := pg_get_serial_sequence('public.' || t.table_name, 'id');
        IF seq IS NOT NULL THEN
            EXECUTE format('SELECT setval(%L, COALESCE((SELECT MAX(id) FROM %I), 1))', seq, t.table_name);
        END IF;
    END LOOP;
END $$;

-- ==========================================
-- 12. GRANT ALL PRIVILEGES ON TABLES, SEQUENCES, AND FUNCTIONS
-- ==========================================
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres, anon, authenticated, service_role;
